language: ruby
before_script:
  - bundle exec rake db:create db:migrate db:seed
rvm:
  - 1.9.3

deploy:
  provider: heroku
  app: mysterious-bastion-5492
  api_key: d75dc036-e1dc-4746-9faf-7e0c71eaf6cf
